/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type FetchScheduleTypeEnum = "ask" | "best" | "job" | "new" | "show" | "top" | "updates";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type StoryTypeEnum = "job" | "story";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TopStoryTypeEnum = "ask" | "best" | "job" | "new" | "show" | "top";

export interface Ask {
  createdAt: Generated<Timestamp>;
  dead: boolean;
  deletedAt: Timestamp | null;
  descendants: number;
  hnId: number;
  id: Generated<number>;
  score: number;
  title: string;
  updatedAt: Generated<Timestamp>;
  url: string | null;
  userId: number;
}

export interface Comment {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  hnId: number;
  id: Generated<number>;
  order: Generated<number>;
  parentId: number | null;
  storyId: number;
  text: string | null;
  updatedAt: Generated<Timestamp>;
  userId: number | null;
}

export interface FetchSchedule {
  createdAt: Generated<Timestamp>;
  finishedAt: Timestamp | null;
  id: Generated<number>;
  totalItems: number | null;
  type: FetchScheduleTypeEnum;
  updatedAt: Generated<Timestamp>;
}

export interface KnexMigrations {
  batch: number | null;
  id: Generated<number>;
  migrationTime: Timestamp | null;
  name: string | null;
}

export interface KnexMigrationsLock {
  index: Generated<number>;
  isLocked: number | null;
}

export interface Pollopt {
  createdAt: Generated<Timestamp>;
  hnId: number;
  id: Generated<number>;
  score: Generated<number>;
  storyId: number;
  text: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Story {
  createdAt: Generated<Timestamp>;
  dead: boolean;
  deletedAt: Timestamp | null;
  descendants: number;
  hnId: number;
  id: Generated<number>;
  score: number;
  storyType: Generated<StoryTypeEnum>;
  text: string | null;
  title: string | null;
  updatedAt: Generated<Timestamp>;
  url: string | null;
  userId: number | null;
}

export interface TopStory {
  hnId: number;
  id: Generated<number>;
  order: Generated<number>;
  type: TopStoryTypeEnum;
}

export interface User {
  about: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  karma: number | null;
  updatedAt: Generated<Timestamp | null>;
  username: string;
}

export interface DB {
  ask: Ask;
  comment: Comment;
  fetchSchedule: FetchSchedule;
  knexMigrations: KnexMigrations;
  knexMigrationsLock: KnexMigrationsLock;
  pollopt: Pollopt;
  story: Story;
  topStory: TopStory;
  user: User;
}
